const tools = [
  { href: '/regex', title: 'Regex Tester', desc: 'Test & visualize regular expressions with live match highlighting', icon: '◉', cat: 'Text' },
  { href: '/tools/case', title: 'Case Converter', desc: 'Transform text between uppercase, lowercase, camelCase, snake_case & more', icon: 'Aa', cat: 'Text' },
  { href: '/tools/diff', title: 'Diff Checker', desc: 'Compare two texts side by side and highlight differences', icon: '⇔', cat: 'Text' },
  { href: '/tools/stats', title: 'Text Statistics', desc: 'Analyze word count, characters, sentences, reading time & more', icon: 'Σ', cat: 'Text' },
  { href: '/tools/lorem', title: 'Lorem Ipsum Generator', desc: 'Generate placeholder text for mockups and designs', icon: '¶', cat: 'Text' },
  { href: '/tools/sorter', title: 'Text Sorter', desc: 'Sort lines alphabetically, by length, or randomize', icon: '⇕', cat: 'Text' },
  { href: '/tools/slugify', title: 'Slugify', desc: 'Convert text to URL-friendly slugs and identifiers', icon: '§', cat: 'Text' },
  { href: '/tools/replace', title: 'Find & Replace', desc: 'Search and replace text with optional regex support', icon: '✎', cat: 'Text' },
  { href: '/tools/reverser', title: 'Text Reverser', desc: 'Reverse, flip and transform text in multiple ways', icon: '↔', cat: 'Text' },
  { href: '/tools/regex-explain', title: 'Regex Explainer', desc: 'Understand regex patterns with plain-English breakdowns', icon: '◉', cat: 'Text' },
  { href: '/tools/wordcount', title: 'Word Counter', desc: 'Detailed text statistics with word frequency analysis', icon: 'Wc', cat: 'Text' },
  { href: '/tools/morse', title: 'Morse Code Converter', desc: 'Convert text to and from Morse code', icon: '···', cat: 'Text' },
  { href: '/tools/palindrome', title: 'Palindrome Checker', desc: 'Check if text is a palindrome with advanced analysis', icon: '⇔', cat: 'Text' },
  { href: '/pdf/merge', title: 'PDF Merger', desc: 'Merge multiple PDFs with drag-and-drop reordering', icon: '⊞', cat: 'PDF' },
  { href: '/tools/pdf-split', title: 'Split PDF', desc: 'Extract pages into separate PDF files', icon: '⇗', cat: 'PDF' },
  { href: '/tools/pdf-remove', title: 'Remove Pages', desc: 'Delete unwanted pages from a PDF document', icon: '✕', cat: 'PDF' },
  { href: '/tools/pdf-rotate', title: 'Rotate PDF', desc: 'Rotate individual pages in a PDF', icon: '⟳', cat: 'PDF' },
  { href: '/tools/pdf-protect', title: 'PDF Protect & Unlock', desc: 'Add or remove password protection from PDFs', icon: '⚷', cat: 'PDF' },
  { href: '/tools/jpg-to-pdf', title: 'JPG to PDF', desc: 'Convert images into a PDF document', icon: '▤', cat: 'PDF' },
  { href: '/tools/pdf-to-md', title: 'PDF to Markdown', desc: 'Extract text from PDF files as clean Markdown', icon: '⇩', cat: 'PDF' },
  { href: '/tools/md-to-pdf', title: 'Markdown to PDF', desc: 'Write Markdown and export as a styled PDF', icon: '⇧', cat: 'PDF' },
  { href: '/converter/universal', title: 'Universal Converter', desc: 'Convert JSON, YAML, Base64, and URL formats', icon: '⇄', cat: 'Code' },
  { href: '/tools/json', title: 'JSON Tools', desc: 'Format, validate, and minify JSON data', icon: '{}', cat: 'Code' },
  { href: '/tools/base', title: 'Base Converter', desc: 'Convert between binary, octal, decimal, and hexadecimal', icon: '0x', cat: 'Code' },
  { href: '/tools/uuid', title: 'UUID Generator', desc: 'Generate UUID v4 & v7 in bulk', icon: '⦿', cat: 'Code' },
  { href: '/tools/urlencode', title: 'URL Encoder/Decoder', desc: 'Encode and decode URLs and query strings', icon: '⇄', cat: 'Code' },
  { href: '/tools/jwt', title: 'JWT Debugger', desc: 'Decode and inspect JWT tokens client-side', icon: '◈', cat: 'Code' },
  { href: '/tools/html-preview', title: 'HTML Preview', desc: 'Render and preview HTML/CSS/JS in a live sandbox', icon: '◩', cat: 'Code' },
  { href: '/tools/json-csv', title: 'JSON to CSV', desc: 'Convert between JSON and CSV formats', icon: '⇅', cat: 'Code' },
  { href: '/tools/html-entities', title: 'HTML Entities', desc: 'Encode and decode HTML special characters', icon: '&', cat: 'Code' },
  { href: '/tools/markdown-preview', title: 'Markdown Preview', desc: 'Live preview of rendered markdown with split view', icon: 'M↓', cat: 'Code' },
  { href: '/tools/base64', title: 'Base64 Encoder/Decoder', desc: 'Encode and decode Base64 text and files', icon: 'B64', cat: 'Code' },
  { href: '/tools/css-minify', title: 'CSS Minifier', desc: 'Minify CSS and compare size savings', icon: 'CSS', cat: 'Code' },
  { href: '/tools/sql-formatter', title: 'SQL Formatter', desc: 'Format SQL queries with proper indentation', icon: 'SQL', cat: 'Code' },
  { href: '/tools/yaml', title: 'YAML Formatter', desc: 'Format, validate, and convert between YAML and JSON', icon: 'YML', cat: 'Code' },
  { href: '/tools/xml-formatter', title: 'XML Formatter', desc: 'Format and minify XML documents', icon: 'XML', cat: 'Code' },
  { href: '/tools/html-formatter', title: 'HTML Formatter', desc: 'Format and beautify HTML markup', icon: 'HTML', cat: 'Code' },
  { href: '/tools/hash', title: 'Hash Generator', desc: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes', icon: '#', cat: 'Security' },
  { href: '/tools/password', title: 'Password Generator', desc: 'Generate strong passwords with strength meter', icon: '⚷', cat: 'Security' },
  { href: '/tools/encrypt', title: 'Encryption Tools', desc: 'Encrypt and decrypt text with AES via Web Crypto API', icon: '⚔', cat: 'Security' },
  { href: '/tools/bcrypt', title: 'SHA Hash Verifier', desc: 'Generate and verify SHA-256 hashes with salt', icon: '✓', cat: 'Security' },
  { href: '/tools/otp', title: 'OTP Generator', desc: 'Generate TOTP codes for two-factor authentication', icon: '⊕', cat: 'Security' },
  { href: '/tools/color', title: 'Color Converter', desc: 'Convert between Hex, RGB, HSL with live preview', icon: '◐', cat: 'Design' },
  { href: '/tools/gradient', title: 'Gradient Generator', desc: 'Create beautiful CSS gradients with live preview', icon: '◑', cat: 'Design' },
  { href: '/tools/shadows', title: 'Box Shadow Generator', desc: 'Design and preview CSS box shadows interactively', icon: '▨', cat: 'Design' },
  { href: '/tools/radius', title: 'Border Radius Generator', desc: 'Visual border-radius editor with presets', icon: '◧', cat: 'Design' },
  { href: '/tools/palette', title: 'Color Palette', desc: 'Generate harmonious color palettes from a seed color', icon: '◐', cat: 'Design' },
  { href: '/tools/typography', title: 'Typography Scale', desc: 'Generate modular typography scales for your projects', icon: 'T', cat: 'Design' },
  { href: '/tools/filter', title: 'CSS Filter Generator', desc: 'Create and preview CSS filter effects visually', icon: '◑', cat: 'Design' },
  { href: '/tools/font-preview', title: 'Font Preview', desc: 'Preview and compare system fonts with custom text', icon: 'F', cat: 'Design' },
  { href: '/tools/spinner', title: 'Loading Spinner', desc: 'Generate CSS loading spinners and animations', icon: '⟳', cat: 'Design' },
  { href: '/tools/svg-viewer', title: 'SVG Viewer', desc: 'Paste, preview, and inspect SVG code', icon: '◇', cat: 'Design' },
  { href: '/tools/css-anim', title: 'CSS Animation Generator', desc: 'Create and preview CSS keyframe animations', icon: '▶', cat: 'Design' },
  { href: '/tools/unit', title: 'Unit Converter', desc: 'Convert between length, weight, temperature, data, and speed units', icon: '⇅', cat: 'Math' },
  { href: '/tools/calculator', title: 'Calculator', desc: 'A full-featured calculator with history', icon: '⊕', cat: 'Math' },
  { href: '/tools/percent', title: 'Percentage Calculator', desc: 'Calculate percentages, ratios, and changes', icon: '%', cat: 'Math' },
  { href: '/tools/random', title: 'Random Number Generator', desc: 'Generate random numbers with custom ranges', icon: '⊕', cat: 'Math' },
  { href: '/tools/tip', title: 'Tip Calculator', desc: 'Calculate tips and split bills between people', icon: '%', cat: 'Math' },
  { href: '/tools/primes', title: 'Prime Checker', desc: 'Check if a number is prime with factorization', icon: 'P', cat: 'Math' },
  { href: '/tools/numwords', title: 'Number to Words', desc: 'Convert numbers to English words and Roman numerals', icon: 'N', cat: 'Math' },
  { href: '/tools/geometry', title: 'Geometry Calculator', desc: 'Calculate area, perimeter, and volume of shapes', icon: '◇', cat: 'Math' },
  { href: '/tools/fibonacci', title: 'Fibonacci Generator', desc: 'Generate Fibonacci sequences with golden ratio', icon: 'φ', cat: 'Math' },
  { href: '/tools/timestamp', title: 'Timestamp Converter', desc: 'Convert Unix timestamps to readable dates', icon: '⏱', cat: 'Date' },
  { href: '/tools/timezone', title: 'Timezone Converter', desc: 'Convert times between different timezones', icon: '⏰', cat: 'Date' },
  { href: '/tools/datediff', title: 'Date Difference', desc: 'Calculate the difference between two dates', icon: '⇆', cat: 'Date' },
  { href: '/tools/mac', title: 'MAC Generator', desc: 'Generate random MAC addresses with custom prefixes', icon: '↗', cat: 'Network' },
  { href: '/tools/ip', title: 'IP Info Lookup', desc: 'Parse and inspect IPv4 and IPv6 address details', icon: '◎', cat: 'Network' },
  { href: '/tools/subnet', title: 'Subnet Calculator', desc: 'Calculate subnet masks, ranges, and host counts', icon: '⊞', cat: 'Network' },
  { href: '/tools/ports', title: 'Port Reference', desc: 'Searchable reference of common TCP/UDP ports', icon: '⇋', cat: 'Network' },
  { href: '/tools/latency', title: 'Latency Calculator', desc: 'Calculate network latency and RTT over distance', icon: '∼', cat: 'Network' },
  { href: '/tools/cron', title: 'Cron Parser', desc: 'Parse cron expressions and preview execution times', icon: '⏱', cat: 'DevOps' },
  { href: '/tools/http-status', title: 'HTTP Status Codes', desc: 'Searchable reference of all HTTP status codes', icon: '200', cat: 'DevOps' },
  { href: '/tools/git-ref', title: 'Git Reference', desc: 'Searchable reference of common Git commands', icon: 'G', cat: 'DevOps' },
  { href: '/tools/qr', title: 'QR Code Generator', desc: 'Generate QR codes from text or URLs', icon: '▦', cat: 'Media' },
  { href: '/tools/imageb64', title: 'Image to Base64', desc: 'Convert images to Base64-encoded data URIs', icon: '▣', cat: 'Media' },
  { href: '/tools/aspect', title: 'Aspect Ratio Calculator', desc: 'Calculate ratios and dimensions for any screen size', icon: '▬', cat: 'Media' },
  { href: '/tools/placeholder', title: 'Image Placeholder', desc: 'Generate placeholder images as inline SVGs', icon: '▯', cat: 'Media' },
  { href: '/tools/color-picker', title: 'Image Color Picker', desc: 'Pick colors from uploaded images with magnifier', icon: '◎', cat: 'Media' },
  { href: '/tools/age', title: 'Age Calculator', desc: 'Calculate exact age with zodiac and fun stats', icon: '◎', cat: 'Date' },
  { href: '/tools/workdays', title: 'Business Days', desc: 'Calculate workdays between dates excluding holidays', icon: '⇆', cat: 'Date' },
  { href: '/tools/worldclock', title: 'World Clock', desc: 'Live clocks for multiple timezones around the world', icon: '◉', cat: 'Date' },
  { href: '/tools/weeknum', title: 'Week Number', desc: 'Calculate ISO week number and day-of-year stats', icon: 'Wk', cat: 'Date' },
  { href: '/tools/decide', title: 'Decision Maker', desc: 'Coin flip, dice roll, yes/no, and custom picker', icon: '?', cat: 'Fun' },
  { href: '/tools/dice', title: 'Dice Roller', desc: 'Roll multiple dice with realistic animations', icon: '⚄', cat: 'Fun' },
  { href: '/tools/emoji-search', title: 'Emoji Search', desc: 'Search and copy emojis by name or keyword', icon: '☺', cat: 'Fun' },
  { href: '/tools/fake-data', title: 'Fake Data Generator', desc: 'Generate mock names, emails, phones & more', icon: 'D', cat: 'Code' },
  { href: '/tools/tts', title: 'Text to Speech', desc: 'Read text aloud with voice, rate & pitch controls', icon: '♫', cat: 'Media' },
  { href: '/tools/drawing-board', title: 'Drawing Board', desc: 'Freehand drawing canvas with color & brush control', icon: '✏', cat: 'Design' },
  { href: '/tools/image-resizer', title: 'Image Resizer', desc: 'Resize images by dimensions with aspect ratio lock', icon: '⧉', cat: 'Media' },
  { href: '/tools/countdown', title: 'Countdown Timer', desc: 'Set a timer with presets, pause, and audible alert', icon: '⏳', cat: 'Fun' },
  { href: '/tools/color-blindness', title: 'Color Blindness Simulator', desc: 'Simulate protanopia, deuteranopia, tritanopia & more', icon: '◉', cat: 'Design' },
  { href: '/tools/scratchpad', title: 'Scratchpad', desc: 'Quick notes that auto-save to your browser', icon: '✍', cat: 'Text' },
  { href: '/tools/html-minify', title: 'HTML Minifier', desc: 'Strip comments, whitespace & reduce HTML file size', icon: 'Hm', cat: 'Code' },
  { href: '/tools/stopwatch', title: 'Stopwatch', desc: 'Count up with lap times and millisecond precision', icon: '⌚', cat: 'Fun' },
  { href: '/tools/contrast', title: 'Color Contrast Checker', desc: 'Check WCAG AA/AAA compliance between two colors', icon: '◐', cat: 'Design' },
  { href: '/tools/url-parser', title: 'URL Parser', desc: 'Parse URLs into components and query parameters', icon: '⇉', cat: 'Code' },
  { href: '/tools/sci-calc', title: 'Scientific Calculator', desc: 'Advanced math with trig, log, factorial & more', icon: '√', cat: 'Math' },
  { href: '/tools/image-crop', title: 'Image Cropper', desc: 'Select and crop a region from any image', icon: '⊟', cat: 'Media' },
  { href: '/tools/device-info', title: 'Device Info', desc: 'View browser, screen, network & system details', icon: 'ℹ', cat: 'System' },
  { href: '/tools/calendar', title: 'Calendar', desc: 'Monthly calendar view with navigation', icon: '◰', cat: 'Date' },
  { href: '/tools/json-to-ts', title: 'JSON to TypeScript', desc: 'Generate TypeScript interfaces from JSON objects', icon: 'TS', cat: 'Code' },
  { href: '/tools/text-encoder', title: 'Text Encoder', desc: 'Encode text as binary, hex, octal & decimal char codes', icon: '01', cat: 'Code' },
  { href: '/tools/color-harmonies', title: 'Color Harmonies', desc: 'Generate complementary, triadic, tetradic & analogous colors', icon: '◐', cat: 'Design' },
  { href: '/tools/battery', title: 'Battery Info', desc: 'View battery level, charging status and estimated time', icon: '⚡', cat: 'System' },
  { href: '/tools/image-filter', title: 'Image Filters', desc: 'Apply grayscale, sepia & invert filters with adjustable intensity', icon: '◑', cat: 'Media' },
  { href: '/tools/stt', title: 'Speech to Text', desc: 'Transcribe speech in real-time using your microphone', icon: '♩', cat: 'Media' },
  { href: '/tools/pomodoro', title: 'Pomodoro Timer', desc: 'Focus timer with work/break intervals and session tracking', icon: '⏲', cat: 'Fun' },
  { href: '/tools/color-names', title: 'CSS Color Names', desc: 'Browse and search all 148 named CSS colors with preview', icon: '◐', cat: 'Design' },
  { href: '/tools/css-units', title: 'CSS Units Converter', desc: 'Convert between px, em, rem, vw, vh, pt, cm, mm & more with live preview', icon: '⌗', cat: 'Code' },
  { href: '/tools/credit-card', title: 'Credit Card Validator', desc: 'Validate card numbers with Luhn algorithm and detect card type', icon: '⌘', cat: 'Security' },
  { href: '/tools/moon-phase', title: 'Moon Phase', desc: 'Find moon phase, illumination and age for any date', icon: '☾', cat: 'Date' },
  { href: '/tools/resolution', title: 'Resolution Calculator', desc: 'Calculate aspect ratio, megapixels, PPI and pixel pitch', icon: '□', cat: 'Media' },
  { href: '/tools/http-request', title: 'HTTP Request Builder', desc: 'Send HTTP requests with custom method, headers and body', icon: '⇶', cat: 'Network' },
  { href: '/tools/html2md', title: 'HTML to Markdown', desc: 'Convert HTML snippets to clean Markdown', icon: 'H↓', cat: 'Code' },
  { href: '/tools/ascii-art', title: 'ASCII Art Generator', desc: 'Transform text into ASCII art with multiple styles', icon: '▓', cat: 'Fun' },
  { href: '/tools/gzip', title: 'GZip Compressor', desc: 'Compress and decompress text with gzip', icon: '⊡', cat: 'Code' },
  { href: '/tools/box-model', title: 'CSS Box Model', desc: 'Visualize and generate CSS margin, border and padding', icon: '▢', cat: 'Design' },
  { href: '/tools/storage', title: 'Storage Explorer', desc: 'Browse, search, add and delete browser localStorage and sessionStorage', icon: '◫', cat: 'System' },
  { href: '/tools/svg-to-jsx', title: 'SVG to JSX', desc: 'Convert SVG markup to React JSX components', icon: '◈', cat: 'Code' },
  { href: '/tools/isbn', title: 'ISBN Validator', desc: 'Validate ISBN-10 and ISBN-13 with check digit & format conversion', icon: 'ISBN', cat: 'Code' },
  { href: '/tools/text-shadow', title: 'Text Shadow Generator', desc: 'Create multi-layer CSS text shadows with live preview', icon: 'T', cat: 'Design' },
  { href: '/tools/metronome', title: 'Metronome', desc: 'Audio metronome with BPM control and time signatures', icon: '♩', cat: 'Media' },
  { href: '/tools/audio-recorder', title: 'Audio Recorder', desc: 'Record audio from your microphone and download as WebM', icon: '♪', cat: 'Media' },
  { href: '/tools/keyboard', title: 'Keyboard Tester', desc: 'Test key presses with a visual keyboard and event log', icon: '⌨', cat: 'System' },
  { href: '/tools/flexbox', title: 'Flexbox Generator', desc: 'Visual CSS flexbox layout builder with live preview', icon: '≡', cat: 'Design' },
  { href: '/tools/rsa', title: 'RSA Key Generator', desc: 'Generate RSA public/private key pairs in PEM format', icon: '⚷', cat: 'Security' },
  { href: '/tools/ciphers', title: 'Ciphers', desc: 'Encode and decode text with Caesar, Atbash, ROT13 & Vigenere', icon: '⚔', cat: 'Security' },
  { href: '/tools/grid', title: 'CSS Grid Generator', desc: 'Visual CSS grid layout builder with live preview', icon: '⊞', cat: 'Design' },
  { href: '/tools/transition', title: 'Transition Generator', desc: 'Create and preview CSS transitions interactively', icon: '▶', cat: 'Design' },
  { href: '/tools/palette-from-image', title: 'Palette from Image', desc: 'Extract dominant colors from any image', icon: '◐', cat: 'Media' },
  { href: '/tools/image-compare', title: 'Image Comparer', desc: 'Compare two images with an interactive slider', icon: '⇔', cat: 'Media' },
  { href: '/tools/dotenv', title: 'Dotenv Parser', desc: 'Parse .env files and convert to JSON or YAML', icon: '.env', cat: 'Code' },
  { href: '/tools/reaction-time', title: 'Reaction Time Test', desc: 'Measure your reaction speed with click timing', icon: '⏱', cat: 'Fun' },
  { href: '/tools/typing-speed', title: 'Typing Speed Test', desc: 'Test your WPM typing speed and accuracy', icon: '⌨', cat: 'Fun' },
  { href: '/tools/piano', title: 'Piano', desc: 'Play piano with keyboard or click using Web Audio', icon: '♫', cat: 'Media' },
  { href: '/tools/roman', title: 'Roman Numeral Converter', desc: 'Convert between numbers and Roman numerals', icon: 'R', cat: 'Math' },
  { href: '/tools/outline', title: 'CSS Outline Generator', desc: 'Visual CSS outline property editor with preview', icon: '◎', cat: 'Design' },
  { href: '/tools/click-speed', title: 'Click Speed Test', desc: 'Test how fast you can click in a timed session', icon: '◎', cat: 'Fun' },
  { href: '/tools/bmi', title: 'BMI Calculator', desc: 'Calculate BMI, BMR and weight category', icon: '◉', cat: 'Math' },
  { href: '/tools/color-temp', title: 'Color Temperature', desc: 'Convert between Kelvin color temperature and RGB', icon: '◐', cat: 'Design' },
  { href: '/tools/investment', title: 'Investment Calculator', desc: 'Project investment growth with compound interest', icon: '%', cat: 'Math' },
  { href: '/tools/dedup', title: 'Duplicate Line Remover', desc: 'Remove duplicate, empty or unwanted lines from text', icon: '≡', cat: 'Text' },
  { href: '/tools/graphql', title: 'GraphQL Formatter', desc: 'Format and indent GraphQL queries and mutations', icon: '⚡', cat: 'Code' },
  { href: '/tools/noise', title: 'Noise Generator', desc: 'Generate white, pink, and brown noise for focus or sleep', icon: '♪', cat: 'Media' },
  { href: '/tools/breathing', title: 'Breathing Exercise', desc: 'Guided breathing patterns for relaxation and focus', icon: '○', cat: 'Fun' },
  { href: '/tools/scrollbar', title: 'Scrollbar CSS Generator', desc: 'Create custom scrollbar styles with live preview', icon: '▤', cat: 'Design' },
  { href: '/tools/cursors', title: 'CSS Cursor Reference', desc: 'Browse and test all CSS cursor values', icon: '✙', cat: 'Design' },
  { href: '/tools/code-beautifier', title: 'Code Beautifier', desc: 'Auto-indent and beautify JS, HTML and CSS code', icon: '{ }', cat: 'Code' },
  { href: '/tools/data-size', title: 'Data Size Converter', desc: 'Convert between bytes, KB, MB, GB, TB and PB', icon: '⇅', cat: 'Math' },
  { href: '/tools/semver', title: 'SemVer Compare', desc: 'Compare and validate semantic version strings', icon: 'SV', cat: 'Code' },
  { href: '/tools/mq-builder', title: 'Media Query Builder', desc: 'Generate responsive CSS media queries visually', icon: '▦', cat: 'Design' },
  { href: '/tools/css-vars', title: 'CSS Variables Generator', desc: 'Generate and manage CSS custom properties', icon: '--', cat: 'Design' },
  { href: '/tools/docker', title: 'Docker Compose Builder', desc: 'Generate docker-compose.yml from preset services', icon: '⎈', cat: 'DevOps' },
  { href: '/tools/b64image', title: 'Base64 Image Viewer', desc: 'Decode and preview Base64-encoded images inline', icon: '▣', cat: 'Media' },
  { href: '/tools/changelog', title: 'Changelog Generator', desc: 'Generate formatted changelogs from entries', icon: '≡', cat: 'DevOps' },
  { href: '/tools/env-editor', title: 'Env File Editor', desc: 'Parse, edit and export .env files to JSON or shell', icon: '⚙', cat: 'System' },
  { href: '/tools/clip-path', title: 'CSS Clip Path Generator', desc: 'Visual clip-path shape builder with live preview', icon: '◇', cat: 'Design' },
  { href: '/tools/pwd-analyzer', title: 'Password Strength Analyzer', desc: 'Analyze password strength with detailed feedback and entropy', icon: '⚷', cat: 'Security' },
  { href: '/tools/bandwidth', title: 'Bandwidth Test', desc: 'Estimate your connection speed with real-time latency', icon: '∼', cat: 'Network' },
  { href: '/tools/k8s-gen', title: 'K8s Deployment Generator', desc: 'Generate Kubernetes Deployment and Service YAML', icon: '☸', cat: 'DevOps' },
  { href: '/tools/screen-picker', title: 'Screen Color Picker', desc: 'Pick colors from your screen with the EyeDropper API', icon: '◎', cat: 'System' },
  { href: '/tools/barcode', title: 'Barcode Generator', desc: 'Generate CODE128 barcodes from text or numbers', icon: '▆', cat: 'Media' },
  { href: '/tools/terraform', title: 'Terraform Formatter', desc: 'Format and indent HashiCorp HCL configuration files', icon: '⊞', cat: 'DevOps' },
  { href: '/tools/nginx', title: 'Nginx Config Builder', desc: 'Generate nginx server blocks with location directives', icon: '↗', cat: 'DevOps' },
  { href: '/tools/table-gen', title: 'HTML Table Generator', desc: 'Visually build HTML tables with headers and data', icon: '⊞', cat: 'Code' },
  { href: '/tools/marquee', title: 'CSS Marquee Generator', desc: 'Create scrolling text marquee animations in CSS', icon: '▶', cat: 'Design' },
  { href: '/tools/csv-viewer', title: 'CSV Viewer', desc: 'Paste CSV data and view it as a formatted table', icon: '▦', cat: 'Code' },
  { href: '/tools/pem-viewer', title: 'PEM Certificate Viewer', desc: 'Decode and inspect PEM certificate headers and metadata', icon: '⚷', cat: 'Security' },
  { href: '/tools/notify', title: 'Notification Tester', desc: 'Test browser push notifications with custom title and body', icon: 'ℹ', cat: 'System' },
  { href: '/tools/ntp', title: 'NTP Clock', desc: 'Display precise network time synced from worldtimeapi', icon: '◉', cat: 'Network' },
  { href: '/tools/date-range', title: 'Date Range Calculator', desc: 'Calculate duration between dates in multiple units', icon: '⇆', cat: 'Date' },
  { href: '/tools/average', title: 'Average Calculator', desc: 'Calculate mean, median, mode, min, max and range', icon: 'Σ', cat: 'Math' },
  { href: '/tools/quotes', title: 'Quote Generator', desc: 'Display random inspirational quotes from a curated collection', icon: '❝', cat: 'Fun' },
  { href: '/tools/clipboard', title: 'Clipboard Manager', desc: 'Copy, paste and manage clipboard history in your browser', icon: '📋', cat: 'System' },
  { href: '/tools/event-countdown', title: 'Event Countdown', desc: 'Live countdown timer to a specific date and time', icon: '⏳', cat: 'Date' },
  { href: '/tools/aspect-gen', title: 'CSS Aspect Ratio Generator', desc: 'Generate aspect-ratio CSS from width and height dimensions', icon: '▬', cat: 'Design' },
  { href: '/tools/pdf-meta', title: 'PDF Meta Reader', desc: 'Extract and display metadata from uploaded PDF files', icon: 'PDF', cat: 'PDF' },
  { href: '/tools/cookie-viewer', title: 'Cookie Viewer', desc: 'View, search and clear cookies set by the current site', icon: '🍪', cat: 'System' },
  { href: '/tools/dns-lookup', title: 'DNS Lookup', desc: 'Query DNS records via Cloudflare DNS-over-HTTPS', icon: '◎', cat: 'Network' },
  { href: '/tools/docker-run', title: 'Docker Run Generator', desc: 'Generate docker run commands with ports, volumes and env vars', icon: '⎈', cat: 'DevOps' },
  { href: '/tools/caesar-cipher', title: 'Caesar Cipher', desc: 'Encode and decode text with Caesar cipher and ROT13', icon: '⚔', cat: 'Security' },
  { href: '/tools/memory-stats', title: 'Memory Stats', desc: 'View browser JS heap and device memory usage', icon: '💾', cat: 'System' },
  { href: '/tools/pdf-info', title: 'PDF Info', desc: 'Extract metadata, page count and dimensions from PDF files', icon: 'PDF', cat: 'PDF' },
  { href: '/tools/whois-lookup', title: 'Whois Lookup', desc: 'Query domain registration info via the RDAP protocol', icon: '◎', cat: 'Network' },
  { href: '/tools/k8s-pod', title: 'K8s Pod Generator', desc: 'Generate Kubernetes Pod YAML manifests', icon: '☸', cat: 'DevOps' },
  { href: '/tools/geo-location', title: 'Geolocation', desc: 'Get your current GPS coordinates and location metadata', icon: '🌍', cat: 'System' },
  { href: '/tools/entropy', title: 'Entropy Calculator', desc: 'Calculate password and text entropy in bits with strength meter', icon: '#', cat: 'Security' },
  { href: '/tools/day-counter', title: 'Day Counter', desc: 'Count days, weekdays, weeks and months between two dates', icon: '⇆', cat: 'Date' },
  { href: '/tools/net-info', title: 'Network Info', desc: 'View real-time browser network connection details', icon: '◎', cat: 'Network' },
  { href: '/tools/ci-badge', title: 'CI Badge Generator', desc: 'Generate shields.io badge markdown, HTML and URLs', icon: '⎈', cat: 'DevOps' },
  { href: '/tools/vibration', title: 'Vibration Tester', desc: 'Test device vibration patterns on mobile browsers', icon: '📳', cat: 'System' },
  { href: '/tools/color-guess', title: 'Color Guessing Game', desc: 'Guess the hex code that matches the displayed color', icon: '◐', cat: 'Fun' },
  { href: '/tools/fonts', title: 'Font Viewer', desc: 'List and preview system fonts with custom sample text', icon: 'F', cat: 'System' },
  { href: '/tools/k8s-ingress', title: 'K8s Ingress Generator', desc: 'Generate Kubernetes Ingress YAML with TLS and annotations', icon: '☸', cat: 'DevOps' },
  { href: '/tools/ip-geo', title: 'IP Geolocation', desc: 'Look up geographic location and ISP details for any IP', icon: '◎', cat: 'Network' },
  { href: '/tools/xor-cipher', title: 'XOR Cipher', desc: 'Encrypt and decrypt text using XOR with a key', icon: '⚔', cat: 'Security' },
  { href: '/tools/season', title: 'Season Finder', desc: 'Determine astronomical and meteorological season for any date', icon: '🌸', cat: 'Date' },
  { href: '/tools/url-health', title: 'URL Health Check', desc: 'Check URL reachability and inspect response headers and timing', icon: '◎', cat: 'Network' },
  { href: '/tools/k8s-config', title: 'K8s ConfigMap Generator', desc: 'Generate Kubernetes ConfigMap YAML manifests', icon: '☸', cat: 'DevOps' },
  { href: '/tools/screen-recorder', title: 'Screen Recorder', desc: 'Record your screen, window or browser tab', icon: '📹', cat: 'System' },
  { href: '/tools/time-since', title: 'Time Since', desc: 'Calculate human-readable time elapsed since any date', icon: '⏱', cat: 'Date' },
  { href: '/tools/eight-ball', title: 'Magic 8 Ball', desc: 'Ask a yes/no question and get a classic fortune', icon: '🔮', cat: 'Fun' },
  { href: '/tools/pdf-thumbnail', title: 'PDF Thumbnail', desc: 'Generate thumbnail preview images of PDF pages', icon: '▤', cat: 'PDF' },
  { href: '/tools/jwt-gen', title: 'JWT Generator', desc: 'Generate JWT tokens with custom payload and HMAC secret', icon: '◈', cat: 'Security' },
  { href: '/tools/k8s-secret', title: 'K8s Secret Generator', desc: 'Generate Kubernetes Secret YAML with base64-encoded data', icon: '☸', cat: 'DevOps' },
  { href: '/tools/countup', title: 'Countup Timer', desc: 'Live counter measuring time elapsed since a date', icon: '⏱', cat: 'Date' },
  { href: '/tools/image-grayscale', title: 'Image Grayscale', desc: 'Convert images to grayscale, sepia or invert with adjustable intensity', icon: '◑', cat: 'Media' },
  { href: '/tools/pdf-word-count', title: 'PDF Word Count', desc: 'Count words, characters and sentences in PDF documents', icon: 'Wc', cat: 'PDF' },
  { href: '/tools/bw-convert', title: 'Bandwidth Converter', desc: 'Convert between bps, Kbps, Mbps, Gbps and byte/s rates', icon: '⇅', cat: 'Network' },
  { href: '/tools/hex-converter', title: 'Hex Converter', desc: 'Convert text to hex and hex back to text', icon: '0x', cat: 'Security' },
  { href: '/tools/idle-detector', title: 'Idle Detector', desc: 'Track how long you have been idle without keyboard or mouse', icon: '⏸', cat: 'System' },
  { href: '/tools/fraction', title: 'Fraction Converter', desc: 'Convert decimal numbers to fractions with adjustable precision', icon: '½', cat: 'Math' },
  { href: '/tools/url-extractor', title: 'URL Extractor', desc: 'Extract all URLs from text with deduplication', icon: '⇉', cat: 'Network' },
  { href: '/tools/k8s-hpa', title: 'K8s HPA Generator', desc: 'Generate Kubernetes HorizontalPodAutoscaler YAML', icon: '☸', cat: 'DevOps' },
  { href: '/tools/rps', title: 'Rock Paper Scissors', desc: 'Play rock paper scissors against the computer', icon: '🪨', cat: 'Fun' },
  { href: '/tools/exponent', title: 'Exponent Calculator', desc: 'Calculate powers, nth roots and logarithms', icon: 'ⁿ', cat: 'Math' },
  { href: '/tools/text-pad', title: 'Text Padding', desc: 'Pad text with custom characters on left, right or center', icon: '≡', cat: 'Text' },
  { href: '/tools/crc32', title: 'CRC32 Checksum', desc: 'Calculate CRC32 checksum of any text input', icon: '#', cat: 'Security' },
  { href: '/tools/hangman', title: 'Hangman', desc: 'Guess the hidden word before the hangman is complete', icon: '🎮', cat: 'Fun' },
  { href: '/tools/image-blur', title: 'Image Blur', desc: 'Apply Gaussian blur to images with adjustable radius', icon: '◑', cat: 'Media' },
  { href: '/tools/anniversary', title: 'Anniversary Calculator', desc: 'Count days until the next anniversary or birthday', icon: '🎉', cat: 'Date' },
  { href: '/tools/text-wrap', title: 'Text Wrapper', desc: 'Wrap text to a specific column width in word or char mode', icon: '≡', cat: 'Text' },
  { href: '/tools/binary-encoder', title: 'Binary Encoder', desc: 'Convert text to binary and binary back to text', icon: '01', cat: 'Security' },
  { href: '/tools/docker-clean', title: 'Docker Cleanup', desc: 'Generate Docker cleanup and maintenance commands', icon: '⎈', cat: 'DevOps' },
  { href: '/tools/alarm', title: 'Alarm Clock', desc: 'Set a one-time browser alarm with audio and label', icon: '⏰', cat: 'System' },
  { href: '/tools/word-scramble', title: 'Word Scramble', desc: 'Unscramble the jumbled word in this fun word game', icon: '🔤', cat: 'Fun' },
  { href: '/tools/time-in-words', title: 'Time in Words', desc: 'Convert digital time to human-readable words', icon: '⏰', cat: 'Date' },
  { href: '/tools/combination', title: 'Combination Calculator', desc: 'Calculate nCr combinations, nPr permutations, and factorials', icon: 'C', cat: 'Math' },
  { href: '/tools/cookie-editor', title: 'Cookie Editor', desc: 'View, set and delete browser cookies for the current site', icon: '🍪', cat: 'System' },
  { href: '/tools/dockerfile-gen', title: 'Dockerfile Generator', desc: 'Generate Dockerfiles from preset templates for various runtimes', icon: '⎈', cat: 'DevOps' },
  { href: '/tools/mime-lookup', title: 'MIME Type Lookup', desc: 'Browse and search common MIME types, extensions and descriptions', icon: 'M', cat: 'Network' },
  { href: '/tools/pdf-to-txt', title: 'PDF to TXT', desc: 'Extract plain text from PDF documents using pdf.js', icon: '⇩', cat: 'PDF' },
  { href: '/tools/pdf-text-search', title: 'PDF Text Search', desc: 'Search for text within a PDF document', icon: '🔍', cat: 'PDF' },
  { href: '/tools/ping-monitor', title: 'Ping Monitor', desc: 'Measure response times and reachability of hosts', icon: '📡', cat: 'Network' },
  { href: '/tools/wake-lock', title: 'Wake Lock', desc: 'Keep your screen awake using the Screen Wake Lock API', icon: '☀', cat: 'System' },
  { href: '/tools/k8s-ns-gen', title: 'K8s Namespace Generator', desc: 'Generate Kubernetes Namespace YAML manifests', icon: '☸', cat: 'DevOps' },
  { href: '/tools/cal-convert', title: 'Calendar Converter', desc: 'Convert dates between Gregorian, Hebrew, Islamic and Chinese calendars', icon: '📅', cat: 'Date' },
  { href: '/tools/bpm-tap', title: 'BPM Tapper', desc: 'Tap any key or click to find the beats per minute', icon: '♩', cat: 'Fun' },
  { href: '/tools/levenshtein', title: 'Levenshtein Distance', desc: 'Calculate the edit distance between two strings', icon: 'Δ', cat: 'Text' },
  { href: '/tools/json-minify', title: 'JSON Minifier', desc: 'Minify JSON by removing all unnecessary whitespace', icon: '{}', cat: 'Code' },
  { href: '/tools/cpu-info', title: 'CPU Info', desc: 'View browser CPU core count, architecture and hardware concurrency', icon: '⚙', cat: 'System' },
  { href: '/tools/unicode-inspector', title: 'Unicode Inspector', desc: 'Inspect Unicode character details, codepoints and properties', icon: 'U+', cat: 'Text' },
];

export default tools;
